### ISSUE TITLE
Incorrect calculation of rate_limit if it is already applied and you need to calculate the timer for additional messages

### ISSUE THREAD

**Issue by obervinov** [obervinov/users-package#32]
**Context**
In a situation when a message exceeding the quota for requests is received, _rate_limit_ is applied with the time stamp `now +1 hour'. But all subsequent messages received after the restrictions are applied receive a timestamp according to the same formula `now + 1 hour'.
The result is a situation where after 1 hour 3 will be processed at once (for example) messages, not 1, as specified in the configuration.

![Image](https://github.com/obervinov/users-package/assets/49606362/64760700-780c-48ff-bcf4-eb92da66fa9d)

![Image](https://github.com/obervinov/users-package/assets/49606362/99d6ddd2-b00d-4fb5-a518-5041946efbf3)

requests configuration
```python
        "requests": {
            "requests_per_day": 10,
            "requests_per_hour": 1,
            "random_shift_minutes": 15
        }
```

**To-Do**
- [x] with an already existing limit, depending on the per_hour setting, you need to add `+1 hour` to the already existing rate limit end time
- [x] the request counter should reset to zero only during the end of the timer `rate_limits` in `end_time`
- [x] when calculating the limit end timer for an incoming request (if rate limits is already applied), you need to proceed from the `per_hour` limit on requests if `>1` request per hour is allowed

  ```python
    math.ceil("requests_counters": { "requests_per_hour": 1} / "requests": {"requests_per_hour": 1})
  ```

**Tests**
- [x] add tests to check the recalculation of request counters
- [x] add tests to check the `end_time` timestamp, namely whether the time shift in `end_time` is calculated correctly when the request counter limit is exceeded multiple times
